ClientMVC/Controllers/CustomerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;
using DataModel.Infrastructure;
using DataModel.Models;
using ClientMVC.Filters;
using ClientMVC.Tools;

namespace ClientMVC.Controllers
{
    public class CustomerController : Controller
    {
        private int customer;
        private string connection_str = 
            ConfigurationManager.ConnectionStrings["BooksConnection"].ConnectionString;
        private IdataRepository clientRepo;
        public CustomerController(IdataRepository repository)
        {
            clientRepo = repository;
        }
        [LogAttribute]
        public ActionResult BooksOnHand(int customer_id)
        {
            clientRepo.OpenConnection(connection_str);
            List<Book> models = clientRepo.OnHandBooks(customer_id);
            clientRepo.CloseConnection();
            return View(models);
        }
        public ActionResult takeABook(int book_id, int customer_id)
        {
            clientRepo.OpenConnection(connection_str);
            clientRepo.takeABook(book_id: book_id, customer_id: customer_id);
            clientRepo.CloseConnection();
            return Redirect("/Home/Index");
        }
        public ActionResult giveABook(int book_id)
        {
            clientRepo.OpenConnection(connection_str);
            clientRepo.giveABook(book_id: book_id);
            clientRepo.CloseConnection();
            customer = Tools.AuthorizedInfo.getAuthorized().customer_id;
            return Redirect("/Customer/BooksOnHand/"+ customer);
        }
    }
}

ClientMVC/Controllers/HeaderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ClientMVC.Tools;

namespace ClientMVC.Controllers
{
    public class HeaderController : Controller
    {
        // GET: Header
        public ActionResult GetHeader()
        {
            if (Tools.AuthorizedInfo.IsAuthorized()) {
                string str = AuthorizedInfo.getAuthorized().first_name +
                    AuthorizedInfo.getAuthorized().last_name + " is authorized";
                return PartialView("~/Views/Shared/Login.cshtml", str);
            } else
                return PartialView("~/Views/Header/GetHeader.cshtml");
        }
    }
}

ClientMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Configuration;

using DataModel.Infrastructure;
using DataModel.Models;
using System.Web.Security;
using ClientMVC.Tools;

namespace ClientMVC.Controllers
{
    public class HomeController : Controller
    {
        private string connection_str =
            ConfigurationManager.ConnectionStrings["BooksConnection"].ConnectionString;
        private IdataRepository homeRepo;
        public HomeController(IdataRepository injectedHomeRepo)
        {
            homeRepo = injectedHomeRepo;
        }
        public ActionResult Login(string login, string password)
        {
            // поиск пользователя в бд
            Customer user = null;
            homeRepo.OpenConnection(connection_str);
            user = homeRepo.getAuthorizedClient(login: login, password: password);
            homeRepo.CloseConnection();
            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(user.first_name + user.last_name, true);

                AuthorizedInfo.setAuthorized(user);
                string response = user.first_name + user.last_name + " is authorized";
                ViewBag.customer_id = user.customer_id;
                //return RedirectToAction("BooksOnHand", "Customer", new { customer_id = user.customer_id });
                return PartialView(model: response);
            }
            else
            {
                //    return RedirectToRoute("Default");
                return PartialView(model: login + "is not authorized");
            }
        }
        public ActionResult Index()
        {
            homeRepo.OpenConnection(connection_str);
            var model = homeRepo.AllBooksAsList();
            homeRepo.CloseConnection();
            return View(model);
        }
        public ActionResult BookSearching(string SearchBook, string seeking_str)
        {
            homeRepo.OpenConnection(connection_str);
            var model = homeRepo.WantedBooksByCriterion(new SearchPackage { criterion = SearchBook, value = seeking_str });
            homeRepo.CloseConnection();
            return PartialView(model);
        }
    }
}

ClientMVC/Views/Customer/BooksOnHand.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/Content/HomeIndexStyle.css" rel="stylesheet" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Account</title>
</head>
    <body>
    @model IEnumerable<DataModel.Models.Book>
    <div id="handList">
        @foreach (var pt in Model)
        {
            <p class="handListP"> Author: @pt.author_name </p>
            <p class="handListP"> Name: @pt.book_name  </p>
            <p class="handListP"> ISBN: @pt.ISBN </p>
            <p class="handListP"> Genre: @pt.genre </p>
            @Html.ActionLink(linkText: "returnABook",
    actionName: "giveABook",
    controllerName: "Customer",
    routeValues: new { book_id = pt.book_id },
    htmlAttributes: "");
            <br />
        }
    </div>
    @Html.ActionLink("to Home page","Index","Home")
</body>
</html>

ClientMVC/Views/Header/GetHeader.cshtml
<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
        log in :
        <div id="authorizeHeader">
            @using (Ajax.BeginForm(actionName: "Login", controllerName: "Home",
            routeValues: "",
            ajaxOptions: new AjaxOptions()
            {
                HttpMethod = "Post",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "AuthorizeHeader",
            },
            htmlAttributes: new { id = "AuthorizeForm", style = "display:block" }))
            {
             <span>enter your login</span>
             <input type="text" name="login" class="logInput" />
             <span>enter your password</span>
             <input type="password" name="password" class="logInput" />
             <input type="submit" id="AuthorizeSubmit" value="log in" />
            }
            <div id="AuthorizeHeader"></div>
        </div>
        </div>
    </div>
</div>

ClientMVC/Views/Home/Index.cshtml
<!DOCTYPE html>
<html>
@model IEnumerable<DataModel.Models.Book>
@{
    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "seekByAuthor",
        Value = "BookAuthor"
    });
    listItems.Add(new SelectListItem
    {
        Text = "seekByName",
        Value = "BookName",
        Selected = true
    });
    listItems.Add(new SelectListItem
    {
        Text = "seekByISBN",
        Value = "BookISBN"
    });
}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>VirtualLibrary</title>
    <link href="~/Content/HomeIndexStyle.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-3.1.1.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/ScriptsFromCoder/JSHandlers.js"></script>
</head>
<body>
@{Html.RenderAction("GetHeader", "Header");}
<h2>Index</h2>
<div id="BooksOnHand">
</div>
@using (Ajax.BeginForm(actionName: "BookSearching", controllerName: "Home",
                ajaxOptions: new AjaxOptions
                {
                    HttpMethod = "Post",
                    InsertionMode = InsertionMode.Replace,
                    UpdateTargetId = "BooksOnHand",
                    LoadingElementId = "loading",
                    LoadingElementDuration = 1000
                }))
{
    <span></span>
    @Html.DropDownList("SearchBook", listItems)
    <input type="text" name="seeking_str" />
    <input type="submit" value="Search" />
}
<div id="loading" style="display:none; color:Red; font-weight:bold;">
    <p>Searching...</p>
</div>
<div id="mainList">
    @foreach (var p in Model)
    {
        { Html.RenderPartial("Home_Item", p); }
    }
</div>
</body>
</html>
<script type="text/javascript">
    function formSpecialRequest(book_id){
        alert('SP request');
        var customer = $('#customer_id').val();
        var request = "/Customer/takeABook/" + book_id + '/' + customer;
        return location.href = request;
    }
</script>

ClientMVC/Views/Shared/BookSearching.cshtml
@model IEnumerable<DataModel.Models.Book>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.author_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.book_name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ISBN)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.genre)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.author_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.book_name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ISBN)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.genre)
        </td>
    </tr>
}

</table>

ClientMVC/Views/Shared/Home_Item.cshtml
@model DataModel.Models.Book
    <p class="mainListP"> Author: @Model.author_name </p>
    <p class="mainListP"> Name: @Model.book_name </p>
    <p class="mainListP"> ISBN: @Model.ISBN </p>
    <div class="allowedUser" style="display:none">
    @if (String.IsNullOrEmpty(Model.owner_id.ToString()))
            {
        <a href="javascript:formSpecialRequest(@Model.book_id)">to get</a>
        //formSpecialRequest(book_id)
    }
    else
    {
        @Html.Raw("<span style=" + "color:blue " + ">item is not available to get</span>")
    }
    </div>
    <br />
    

ClientMVC/Views/Shared/Login.cshtml
@model string 
<div id="logOutPart">
    <span>@Model</span>
    <a id="linkAccount" href= "/Customer/BooksOnHand/@ViewBag.customer_id" > my Account </a>
    <a id="logOutLink" href="javascript:LogOutFunc()">log out</a>
    <input type="hidden" id="customer_id" value=@ViewBag.customer_id />
</div>
<script type="text/javascript">
    function LogOutFunc() {
        var form_auto = document.getElementById('AuthorizeForm');
        var form_inputs = document.getElementsByClassName('logInput');
        var forms_transfer_books =
            document.getElementsByClassName('allowedUser');
        var customer = document.getElementById('customer_id');
        //
        customer.value = null;
        for (let f of forms_transfer_books)
        {
            f.style.display = 'none';
        }
        for(let p of form_inputs)
        {
            console.log(p.value);
            p.value = "";
        }
        document.getElementById('logOutPart').remove();
        form_auto.style.display = 'block';
    }
</script>